workflows:
  android-workflow:
    name: Secure Chat - Android
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.nightwalker.securechat"
        SUPABASE_URL: "https://bgbmrtwbndoewwwjxnxa.supabase.co"
        SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYm1ydHdibmRvZXd3d2p4bnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYyODE5OTUsImV4cCI6MjEwMTg1Nzk5NX0.xa0VJg9di1Tm-p6ZmuJSri2kPbsRS1SxoWq4lmJ0CzU"
      android_signing:
        -
